# Generated by Django 2.0.6 on 2018-06-08 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlternativeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dimer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expression', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Monomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('uniprot', models.CharField(max_length=6, unique=True)),
                ('ensg', models.CharField(max_length=15, unique=True)),
                ('gene_name', models.CharField(max_length=30, unique=True)),
                ('subunit', models.CharField(choices=[('alpha', 'alpha'), ('beta', 'beta')], max_length=5)),
                ('alpha_interaction_domain', models.NullBooleanField()),
                ('length', models.IntegerField()),
                ('sequence', models.TextField()),
                ('taxonomy', models.CharField(choices=[('Metazoa', 'Metazoa'), ('Chordata', 'Chordata')], max_length=8, null=True)),
                ('expression', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonomerToStructure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('monomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Monomer')),
            ],
        ),
        migrations.CreateModel(
            name='Pdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdb_id', models.CharField(max_length=4)),
                ('method', models.CharField(choices=[('NMR', 'NMR'), ('X-ray cystallography', 'X-ray cystallography'), ('Cryo-EM', 'Cryo-EM')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='pdb',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Structure'),
        ),
        migrations.AddField(
            model_name='monomertostructure',
            name='structure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Structure'),
        ),
        migrations.AddField(
            model_name='monomer',
            name='structure',
            field=models.ManyToManyField(through='app.MonomerToStructure', to='app.Structure'),
        ),
        migrations.AddField(
            model_name='dimer',
            name='alpha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alpha', to='app.Monomer'),
        ),
        migrations.AddField(
            model_name='dimer',
            name='beta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beta', to='app.Monomer'),
        ),
        migrations.AddField(
            model_name='alternativename',
            name='monomer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Monomer'),
        ),
        migrations.AlterUniqueTogether(
            name='monomertostructure',
            unique_together={('monomer', 'structure')},
        ),
        migrations.AlterUniqueTogether(
            name='dimer',
            unique_together={('alpha', 'beta')},
        ),
        migrations.AlterUniqueTogether(
            name='alternativename',
            unique_together={('monomer', 'name')},
        ),
    ]
