# Generated by Django 2.0.6 on 2018-07-10 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_monomer_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monomer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
