# Generated by Django 2.0.6 on 2018-07-10 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_monomer_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimer',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='monomer',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
