# Generated by Django 2.0.6 on 2018-07-10 11:51

from django.db import migrations


def make_dimer_names(apps, schema_editor):
    """ Populate values for Dimer.name as implemented in Dimer.save(). This is
    to replace the NULL values introduced in the previous migration, to allow
    "null=False" and "unique=True" in the next migration.
    """

    Dimer = apps.get_model("app", "Dimer")

    for dimer in Dimer.objects.all():
        dimer.name = "{0}/{1}".format(dimer.alpha.name, dimer.beta.name)
        dimer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180710_1140'),
    ]

    operations = [
        migrations.RunPython(make_dimer_names),
    ]
