# Generated by Django 2.0.6 on 2018-07-10 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180710_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimer',
            old_name='name',
            new_name='lookup_name',
        ),
    ]
