# Generated by Django 2.0.6 on 2018-07-10 12:10

from django.db import migrations


def rename_dimers(apps, schema_editor):
    """ Rename dimers to format <alpha.name>_<beta.name> instead of
    <alpha.name>/<beta.name>.
    """

    Dimer = apps.get_model("app", "Dimer")

    for dimer in Dimer.objects.all():
        dimer.lookup_name = dimer.lookup_name.replace("/", "_")
        dimer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180710_1209'),
    ]

    operations = [
        migrations.RunPython(rename_dimers),
    ]
