# Generated by Django 2.0.6 on 2018-07-10 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180710_1130'),
        ('app', '0008_auto_20180710_1210'),
    ]

    operations = [
    ]
