# Generated by Django 2.0.6 on 2018-07-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_merge_20180710_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drugs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('marketing_name', models.CharField(blank=True, max_length=30, null=True)),
                ('status', models.CharField(max_length=30)),
                ('drug_type', models.CharField(max_length=30)),
                ('administration', models.CharField(max_length=30)),
                ('ATC_code', models.CharField(max_length=7, unique=True)),
                ('ATC_class', models.CharField(max_length=30)),
                ('launch_year', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('dimer', models.ManyToManyField(to='app.Dimer')),
            ],
        ),
    ]
