# Generated by Django 2.0.6 on 2018-07-16 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_drugs'),
    ]

    atomic = False

    operations = [
        migrations.RenameModel(
            old_name='Drugs',
            new_name='Drug',
        ),
    ]
