# Generated by Django 2.0.6 on 2018-07-16 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180716_0939'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='ATC_code',
            new_name='atc',
        ),
        migrations.RenameField(
            model_name='drug',
            old_name='ATC_class',
            new_name='atc_class',
        ),
    ]
