# Generated by Django 2.0.6 on 2018-07-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20180716_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug',
            name='drugbank',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
