# Generated by Django 2.0.6 on 2018-07-17 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_drug_drugbank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimerToDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dimer')),
            ],
        ),
        migrations.AlterField(
            model_name='drug',
            name='dimer',
            field=models.ManyToManyField(to='app.Drug'),
        ),
        migrations.AlterField(
            model_name='drug',
            name='drug_type',
            field=models.CharField(choices=[('cyclic peptide', 'cyclic peptide'), ('monoclonal antibody', 'monoclonal antibody'), ('small molecule', 'small molecule')], max_length=30),
        ),
        migrations.AddField(
            model_name='dimertodrug',
            name='drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Drug'),
        ),
        migrations.AddField(
            model_name='drug',
            name='dimer2',
            field=models.ManyToManyField(through='app.DimerToDrug', to='app.Dimer'),
        ),
    ]
