# Generated by Django 2.0.6 on 2018-07-17 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20180717_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drug',
            name='dimer',
        ),
    ]
