# Generated by Django 2.0.6 on 2018-07-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_drug_dimer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drug',
            old_name='dimer2',
            new_name='dimer',
        ),
    ]
