# Generated by Django 2.0.6 on 2018-07-23 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20180717_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdb',
            name='structure',
        ),
        migrations.DeleteModel(
            name='Pdb',
        ),
    ]
