# Generated by Django 2.0.6 on 2018-07-24 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20180723_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdb',
            name='alpha_chain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='pdb',
            name='beta_chain',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
