# Generated by Django 2.0.6 on 2018-07-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20180724_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdbtoprotein',
            name='chains',
            field=models.CharField(default="IWon'tExist", max_length=30),
            preserve_default=False,
        ),
    ]
