# Generated by Django 2.0.6 on 2018-07-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_pdbtoprotein_chains'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='species',
            field=models.CharField(default="IWon'tNeedThis", max_length=30),
            preserve_default=False,
        ),
    ]
