# Generated by Django 2.0.6 on 2018-07-24 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_protein_species'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='alpha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdb_alpha', to='app.Monomer'),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='beta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pdb_beta', to='app.Monomer'),
        ),
    ]
