# Generated by Django 2.0.6 on 2018-07-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20180724_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='alpha_chain',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='beta_chain',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
    ]
