# Generated by Django 2.0.6 on 2018-07-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20180725_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='exp_tech',
            field=models.CharField(choices=[('NMR', 'NMR'), ('X-ray', 'X-ray'), ('Electron microscopy', 'Electron microscopy'), ('Model', 'Model')], max_length=20),
        ),
        migrations.AlterField(
            model_name='protein',
            name='species',
            field=models.CharField(max_length=100),
        ),
    ]
