# Generated by Django 2.0.6 on 2018-07-25 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20180725_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdbtoprotein',
            name='chains',
            field=models.CharField(max_length=62),
        ),
    ]
