# Generated by Django 2.0.6 on 2018-08-31 11:13

from django.db import migrations


def populate_proteins(apps, schema_editor):
    """ Populate the Proteins model with Monomer information.
    """

    Monomer = apps.get_model("app", "Monomer")
    Protein = apps.get_model("app", "Protein")

    homo_sapiens = "Homo sapiens"

    for monomer in Monomer.objects.all():

        try:
            protein = Protein.objects.get(uniprot=monomer.uniprot)
            protein.species = homo_sapiens
        except Protein.DoesNotExist:
            Protein.objects.create(
                uniprot=monomer.uniprot,
                species=homo_sapiens,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20180725_0939'),
    ]

    operations = [
        migrations.RunPython(populate_proteins),
    ]
