# Generated by Django 2.0.6 on 2018-08-31 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20180831_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='monomer',
            name='protein',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Protein'),
        ),
    ]
