# Generated by Django 2.0.6 on 2018-08-31 12:14

from django.db import migrations


def populate_monomer_protein(apps, schema_editor):
    """ Populate the protein Fields on the Monomer model.
    """
    Monomer = apps.get_model("app", "Monomer")
    Protein = apps.get_model("app", "Protein")

    for monomer in Monomer.objects.all():

        protein = Protein.objects.get(
            uniprot=monomer.uniprot,
        )
        monomer.protein = protein
        monomer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_monomer_protein'),
    ]

    operations = [
        migrations.RunPython(populate_monomer_protein),
    ]
