# Generated by Django 2.0.6 on 2018-08-31 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20180831_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monomer',
            name='protein',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Protein'),
        ),
    ]
