# Generated by Django 2.0.6 on 2018-08-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alternativename_protein'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='protein',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Protein'),
        ),
    ]
