# Generated by Django 2.0.6 on 2018-08-31 12:28

from django.db import migrations


def populate_alternativename_protein(apps, schema_editor):
    """ Populate the protein fields on the AlternativeName model.
    """

    Protein = apps.get_model("app", "Protein")
    AlternativeName = apps.get_model("app", "AlternativeName")

    for alternative_name in AlternativeName.objects.all():

        protein = Protein.objects.get(
            uniprot=alternative_name.monomer.uniprot,
        )
        alternative_name.protein = protein
        alternative_name.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20180831_1227'),
    ]

    operations = [
        migrations.RunPython(populate_alternativename_protein),
    ]
