# Generated by Django 2.0.6 on 2018-08-31 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_auto_20180831_1231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='alternativename',
            unique_together={('protein', 'name')},
        ),
    ]
