# Generated by Django 2.0.6 on 2018-08-31 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_remove_alternativename_monomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monomer',
            name='uniprot',
        ),
    ]
