# Generated by Django 2.0.6 on 2018-09-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_monomer_uniprot'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimerToProteinInteractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction', models.BooleanField()),
                ('affinity', models.CharField(max_length=128)),
                ('pmid', models.CharField(max_length=8)),
                ('dimer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Dimer')),
            ],
        ),
        migrations.CreateModel(
            name='ProteinInteractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxonomic_group', models.CharField(max_length=128)),
                ('start', models.IntegerField()),
                ('stop', models.IntegerField()),
                ('site_definition', models.CharField(max_length=512)),
                ('structural_state', models.CharField(max_length=512)),
                ('motif', models.CharField(max_length=16)),
                ('pdb', models.CharField(blank=True, max_length=128, null=True)),
                ('dimer', models.ManyToManyField(through='app.DimerToProteinInteractor', to='app.Dimer')),
                ('protein', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Protein')),
            ],
        ),
        migrations.AddField(
            model_name='dimertoproteininteractor',
            name='protein_interactor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ProteinInteractor'),
        ),
    ]
