# Generated by Django 2.0.6 on 2018-09-05 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20180905_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimertoproteininteractor',
            name='affinity',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
