# Generated by Django 2.0.6 on 2018-09-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_auto_20180905_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alternativename',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='protein',
            field=models.ManyToManyField(through='app.PdbToProtein', to='app.Protein'),
        ),
    ]
