# Generated by Django 2.0.6 on 2018-09-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20180905_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteininteractor',
            name='name',
            field=models.CharField(default='TMP_NAME', max_length=128),
            preserve_default=False,
        ),
    ]
