# Generated by Django 2.0.6 on 2018-09-05 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_proteininteractor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteininteractor',
            name='function',
            field=models.TextField(default='TMP_FUNC'),
            preserve_default=False,
        ),
    ]
