# Generated by Django 2.0.6 on 2018-09-08 06:56

from django.db import migrations


def populate_protein_interaction_lookup_names(apps, schema_editor):
    """ Populate the "lookup_name" Fields on the ProteinInteractor model.
    """

    ProteinInteractor = apps.get_model("app", "ProteinInteractor")

    for pi in ProteinInteractor.objects.all():

        # since the "lookup_name" is populated on "save()", calling "save()" is
        # enough
        pi.lookup_name = pi.name.replace(" ", "_")
        pi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_proteininteractor_lookup_name'),
    ]

    operations = [
        migrations.RunPython(populate_protein_interaction_lookup_names),
    ]
