# Generated by Django 2.0.6 on 2018-09-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_auto_20180908_0656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininteractor',
            name='lookup_name',
            field=models.CharField(editable=False, max_length=128, unique=True),
        ),
    ]
