# Generated by Django 2.0.6 on 2018-09-10 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_proteininteractor_annotated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimertoproteininteractor',
            name='reference',
        ),
        migrations.AddField(
            model_name='dimertoproteininteractor',
            name='pmids',
            field=models.CharField(default='TMP_PMID', max_length=512),
            preserve_default=False,
        ),
    ]
