# Generated by Django 2.0.6 on 2018-09-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_auto_20180910_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteininteractor',
            name='lookup_name',
        ),
    ]
