# Generated by Django 2.0.6 on 2018-09-11 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_remove_proteininteractor_lookup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininteractor',
            name='structural_state',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
