# Generated by Django 2.0.6 on 2018-09-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_auto_20180911_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='exp_tech',
            field=models.CharField(choices=[('NMR', 'NMR'), ('X-ray', 'X-ray'), ('Electron microscopy', 'Electron microscopy'), ('Model', 'Model')], max_length=20, verbose_name='Experimental technique'),
        ),
        migrations.AlterField(
            model_name='pdb',
            name='pdb',
            field=models.CharField(max_length=4, unique=True, verbose_name='PDB ID'),
        ),
        migrations.AlterField(
            model_name='proteininteractor',
            name='structural_state',
            field=models.CharField(default='TMP_NULL', max_length=512),
            preserve_default=False,
        ),
    ]
