# Generated by Django 2.0.6 on 2022-07-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0051_auto_20190425_0847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proteininteractor',
            old_name='taxonomic_group',
            new_name='type_of_interaction',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='annotated',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='dimer',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='function',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='motif',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='pdb',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='site_definition',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='start',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='stop',
        ),
        migrations.RemoveField(
            model_name='proteininteractor',
            name='structural_state',
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='type_of_evidence',
            field=models.CharField(default="NA", max_length=3),
            preserve_default=False,
        ),
    ]
