# Generated by Django 2.0.6 on 2022-07-16 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_auto_20220716_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininteractor',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Protein'),
        ),
    ]
