# Generated by Django 2.0.6 on 2022-07-16 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_auto_20220716_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteininteractor',
            name='competitor',
            field=models.CharField(default='NA', max_length=512),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='construct_boundaries',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='eco',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='experimental_method',
            field=models.CharField(default='NA', max_length=512),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='gene_name',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='interacting_region_boundaries',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='interaction_strength',
            field=models.CharField(default='NA', max_length=512),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='interaction_strength_numeral',
            field=models.CharField(default='NA', max_length=512),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='motif',
            field=models.CharField(default='NA', max_length=16),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='notes',
            field=models.TextField(default='NA'),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='oligomerization_state',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='organism',
            field=models.CharField(default='NA', max_length=128),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='pubmed',
            field=models.CharField(default='NA', max_length=50),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='target_integrin',
            field=models.CharField(default='NA', max_length=32),
        ),
        migrations.AddField(
            model_name='proteininteractor',
            name='xref',
            field=models.CharField(default='NA', max_length=512),
        ),
        migrations.AlterField(
            model_name='proteininteractor',
            name='type_of_interaction',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
