# Generated by Django 2.0.6 on 2022-07-16 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_auto_20220716_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininteractor',
            name='motif',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
