# Generated by Django 2.0.6 on 2022-07-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_auto_20220716_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProteinInforamtion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=512)),
                ('alternative_name', models.CharField(default='NA', max_length=512)),
                ('gene_name', models.CharField(default='NA', max_length=128)),
                ('organism', models.CharField(default='NA', max_length=128)),
                ('organism_scientific', models.CharField(default='NA', max_length=512)),
                ('function', models.TextField(default='NA')),
                ('protein', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Protein')),
            ],
        ),
    ]
