# Generated by Django 2.0.6 on 2022-07-17 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_proteininforamtion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProteinInforamtion',
            new_name='ProteinInformation',
        ),
    ]
