# Generated by Django 2.0.6 on 2022-07-19 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_auto_20220717_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='uniprot',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
