# Generated by Django 2.0.6 on 2022-07-22 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_auto_20220719_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdbtoprotein',
            name='chains',
            field=models.CharField(default='-', max_length=62),
        ),
    ]
