# Generated by Django 2.0.6 on 2022-07-22 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0061_auto_20220722_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdb',
            name='other_interactors',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
