# Generated by Django 2.0.6 on 2022-07-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_auto_20220722_0638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='species',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
