# Generated by Django 2.0.6 on 2022-07-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_auto_20220722_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='protein',
            name='peptide',
            field=models.CharField(default='-', max_length=512),
        ),
        migrations.AlterField(
            model_name='protein',
            name='species',
            field=models.CharField(default='N/A', max_length=512),
        ),
        migrations.AlterField(
            model_name='protein',
            name='uniprot',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
