# Generated by Django 2.0.6 on 2022-07-27 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_auto_20220727_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proteininteractor',
            name='name',
        ),
    ]
