# Generated by Django 2.0.6 on 2022-07-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_remove_proteininteractor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='proteininteractor',
            name='name',
            field=models.CharField(default='-', max_length=128),
            preserve_default=False,
        ),
    ]
