# Generated by Django 2.0.6 on 2022-07-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_proteininteractor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proteininteractor',
            name='name',
            field=models.CharField(default='NA', max_length=128),
        ),
    ]
