# Generated by Django 2.0.6 on 2024-07-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_auto_20220728_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimer',
            old_name='notes',
            new_name='function',
        ),
    ]
